---
baseURL: https://ioofkingman.org/
languageCode: en-us
title: Independent Order of Odd Fellows
module:
  imports:
  - path: github.com/theNewDynamic/gohugo-theme-ananke
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 9
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: ''
  site_logo: ''
  description: The last theme you'll ever need. Maybe.
  facebook: ''
  twitter: https://twitter.com/GoHugoIO
  instagram: ''
  youtube: ''
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  background_color_class: bg-black
  featured_image: "/images/1200px-independent_order_of_odd_fellows_-_links_and_eye.jpg"
  recent_posts_number: 2
